# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 40_yr_fire_chunks_by_region.py
# Created on: 2016-04-06 16:54:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
CumulativeDisturbed = "Fire Layers\\CumulativeDisturbed"
BND_ENRITI_AdministrativeRegions_incl_Gw_BWC_range_clip = "boundary lines\\BND_ENRITI_AdministrativeRegions_incl_Gw_BWC_range_clip"
CumulativeDisturbed_Region_Union = "H:\\GIS\\EA\\Boreal Caribou\\FireHistory\\FireHistory2015.gdb\\fire_hist_CAEAC\\CumulativeDisturbed_Region_Union"
CumulativeDisturbed_Region_Union_omit_unburned = "H:\\GIS\\EA\\Boreal Caribou\\FireHistory\\FireHistory2015.gdb\\fire_hist_CAEAC\\CumulativeDisturbed_Region_Union_omit_unburned"
CumulativeDisturbed_Region_Union_omit_unburn_Dissolve = "H:\\GIS\\EA\\Boreal Caribou\\FireHistory\\FireHistory2015.gdb\\fire_hist_CAEAC\\CumulativeDisturbed_Region_Union_omit_unburn_Dissolve"

# Process: Union
arcpy.Union_analysis("'Fire Layers\\CumulativeDisturbed' #;'boundary lines\\BND_ENRITI_AdministrativeRegions_incl_Gw_BWC_range_clip' #", CumulativeDisturbed_Region_Union, "ALL", "", "GAPS")

# Process: Select
arcpy.Select_analysis(CumulativeDisturbed_Region_Union, CumulativeDisturbed_Region_Union_omit_unburned, "FID_CumulativeDisturbed <> -1")

# Process: Dissolve
arcpy.Dissolve_management(CumulativeDisturbed_Region_Union_omit_unburned, CumulativeDisturbed_Region_Union_omit_unburn_Dissolve, "StartYear;EndYear;REGION", "HECTARES FIRST", "MULTI_PART", "DISSOLVE_LINES")

