# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# FireHabitat_Analysis.py
# Created on: 2015-05-11 10:35:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
#
#
#Based on fire history clipped to the Boreal Caribou range
#
#This script starts a 1965 and creates a polygon of all fire years that are less than or equal to 40 years after the fire year by dissolving overlap.
# Then it calculates the area (hectares) of 40 year chunks of burned habitat.
#The first fire year is used to create the append table.
#
# ---------------------------------------------------------------------------

# Import arcpy module

import os
import arcpy
from arcpy import env
arcpy.env.overwriteOutput = True


EnvWksp = arcpy.GetParameterAsText(0)
FireHistory = arcpy.GetParameterAsText(1)
StartYear = int(arcpy.GetParameterAsText(2))
FinalYear = int(arcpy.GetParameterAsText(3))
Outwksp = arcpy.GetParameterAsText(4)

env.workspace = EnvWksp
outWorkspace = Outwksp

Fire40 = StartYear + 40
newField1 = arcpy.AddFieldDelimiters(arcpy.env.workspace, "FIRE_YEAR")
SQLExpr1 = str(newField1) + ">=" + str(StartYear) + " AND " + str(newField1)+ " <= " + str(Fire40)

arcpy.MakeFeatureLayer_management(FireHistory, "FireHist1")
arcpy.SelectLayerByAttribute_management("FireHist1", "NEW_SELECTION", SQLExpr1)

arcpy.Dissolve_management("FireHist1", "FireHist2", "", "", "", "")

#create feature class (target table) to hold calculated values for each year using FireHistory feature class as a template:
spatial_reference = arcpy.Describe(outWorkspace).spatialReference
arcpy.CreateFeatureclass_management(outWorkspace, "CumulativeDisturbed", "Polygon","FireHist2", "DISABLED", "DISABLED", spatial_reference)

arcpy.AddField_management(Outwksp + "\CumulativeDisturbed", "StartYear", "LONG", "", "", "")
arcpy.AddField_management(Outwksp + "\CumulativeDisturbed", "EndYear", "LONG", "", "", "")

arcpy.CalculateField_management(Outwksp + "\CumulativeDisturbed", "StartYear", StartYear, "VB")
arcpy.CalculateField_management(Outwksp + "\CumulativeDisturbed", "EndYear", Fire40, "VB")

#loops through model from NextYear to lastYear. Can change these parameters
LoopYr = StartYear
LoopEnd = FinalYear +1
for x in xrange(LoopYr, LoopEnd):

    FireYear = x
    Fire40 = x + 40
    newField1 = arcpy.AddFieldDelimiters(arcpy.env.workspace, "FIRE_YEAR")

    #Select 40 years of burned habitat after Fire Year

    SQLExpr1 = str(newField1) + ">=" + str(FireYear) + " AND " + str(newField1)+ " <= " + str(Fire40)

    #print x, Fire40

    #Create temporary layer files
    arcpy.MakeFeatureLayer_management(FireHistory, "FireHist1")
    arcpy.SelectLayerByAttribute_management("FireHist1", "NEW_SELECTION", SQLExpr1)


    # Process: Dissolve 40 year selection of  fire habitat
    arcpy.Dissolve_management("FireHist1", "FireHist2", "", "", "", "")

    arcpy.AddField_management("FireHist2", "StartYear", "LONG", "", "", "")
    arcpy.AddField_management("FireHist2", "EndYear", "LONG", "", "", "")

    arcpy.CalculateField_management("FireHist2", "StartYear", FireYear, "VB")
    arcpy.CalculateField_management("FireHist2", "EndYear", Fire40, "VB")


    #Append 40 year selection of habitat to target table
    TargetTable = Outwksp + "\CumulativeDisturbed"
    arcpy.Append_management("FireHist2", TargetTable)

print "script complete"


#Calculate Area in hectares for every year in TargetTable
arcpy.env.outputCoordinateSystem = arcpy.Describe(TargetTable).spatialReference
arcpy.AddGeometryAttributes_management(TargetTable, "AREA", "KILOMETERS", "HECTARES", "")



