# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Dissolve_Clip_Area.py
# Created on: 2016-03-08 09:04:41.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy
from arcpy import env
arcpy.env.overwriteOutput = True
#env.workspace = r"C:\ActiveProjects\FireHistory\FireHistory.gdb"

EnvWksp = arcpy.GetParameterAsText(0)
FireHistory = arcpy.GetParameterAsText(1)
BorealCaribouRange =arcpy.GetParameterAsText(2)
Outwksp = arcpy.GetParameterAsText(3)

env.workspace = EnvWksp
# Local variables:
outFeatureClass = os.path.join(Outwksp, "Firehistory_dissolve_byYear")

#Firehistory_dissolve_byYear = "C:\\ActiveProjects\\FireHistory\\FireHistory.gdb\\CanadaEqualAreaAlbers\\Firehistory_dissolve_byYear"
FireHist_BorealCarRnge = os.path.join(Outwksp, "FireHist_BorealCarRnge")
#FireHist_BorealCarRnge_2 = FireHist_BorealCarRnge

# Process: Dissolve
arcpy.Dissolve_management(FireHistory, outFeatureClass, "FIRE_YEAR", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Clip
arcpy.Clip_analysis(outFeatureClass, BorealCaribouRange, FireHist_BorealCarRnge)

# Process: Add Geometry Attributes
arcpy.AddGeometryAttributes_management(FireHist_BorealCarRnge, "AREA", "", "HECTARES", "")

